# Site settings
title: Fly For Fun
email: mafeifan@qq.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://mafeifan.github.io"
twitter_username: mafei7
github_username:  mafeifan

# Build settings
markdown: kramdown
# use in github
permalink: pretty
# use in local
#highlighter: rouge
